
[general]

#### Address & Root dir
# host = "::"
port = 80
root = "/dist"

#### Logging
log-level = "debug"

#### Cache Control headers
cache-control-headers = false

#### Auto Compression
compression = true

#### Error pages
# page404 = "./public/404.html"
# page50x = "./public/50x.html"
page-fallback = "/dist/index.html"

#### HTTP/2 + TLS
http2 = false
# http2-tls-cert = "some.cert"
# http2-tls-key = "some.key"

#### Security headers
security-headers = true

#### CORS
cors-allow-origins = ""
cors-allow-headers = ""

#### Directory listing
directory-listing = false

#### Directory listing sorting code
directory-listing-order = 6

#### Directory listing content format ("html" or "json")
directory-listing-format = "html"

#### Basich Authentication
# basic-auth = ""

#### File descriptor binding
# fd = ""

#### Worker threads
threads-multiplier = 1

#### Grace period after a graceful shutdown
grace-period = 0

#### Page fallback for 404s
# page-fallback = "some_page.html"

#### Log request Remote Address if available
log-remote-address = false

#### Redirect to trailing slash in the requested directory uri
redirect-trailing-slash = true

#### Check for existing pre-compressed files
compression-static = false

#### Ignore hidden files/directories (dotfiles)
ignore-hidden-files = false

