[workspace]

members = [
    "services/users_service",
    "services/users_service/migration",
    "services/users_service/entities",

    "civilization",
    "civilization/bern",

    "civilization/beijing",

    "services/frontend"
]
