[workspace]

members = [
    "services/users",
    "services/users/migration",
    "services/users/entities",

    "civilization",
    "civilization/scopes_macro",

    "civilization/beijing",

    "civilization/moscow",
    "civilization/moscow/migrations",

    "services/frontend",

]
