apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $app_name-ingress
  namespace: civilization
  annotations:
    kubernetes.io/ingress.class: haproxy
spec:
  rules:
  - host: constellation-project.ru
    http:
      paths:
      - path: /api/$app_name
        pathType: Prefix
        backend:
          service:
            name: $app_name-service
            port:
              number: 80

  tls:
  - secretName: constellation-cert
    hosts:
    - constellation-project.ru